package com.github.mferrer.krotoplus.generators

import com.squareup.kotlinpoet.FileSpec
import kotlinx.coroutines.experimental.channels.Channel

interface FileSpecProducer {

    val fileSpecChannel: Channel<FileSpec>

    companion object {
        const val AutoGenerationDisclaimer = "THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY."
    }
}